DATASET_PATH = "datasets/dogs_normalized__64x64"
LATENT_DIM = 128
BATCH_SIZE = 16
BUFFERED_BATCHES = 20

START_EPISODE = 0

GEN_MODEL = "mod_ext_4upscl"
GEN_WEIGHTS = None
DISC_MODEL = "mod_ext_5layers"
DICS_WEIGHTS = None
LOAD_FROM_CHECKPOINTS = True

NUM_OF_TRAINING_EPOCHS = 100

WEIGHTS_SAVE_INTERVAL = 5
PROGRESS_IMAGE_SAVE_INTERVAL = 1